# Generated by Django 6.0.5 on 2026-05-13 07:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("update", "更新"),
                            ("publish", "发布"),
                            ("unpublish", "撤回"),
                            ("delete", "删除"),
                            ("restore", "还原版本"),
                        ],
                        max_length=40,
                        verbose_name="操作",
                    ),
                ),
                ("target_type", models.CharField(max_length=40, verbose_name="目标类型")),
                ("target_id", models.CharField(max_length=64, verbose_name="目标 ID")),
                ("payload", models.JSONField(default=dict, verbose_name="详情")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="操作时间")),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "审计日志",
                "verbose_name_plural": "审计日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("slug", models.SlugField(allow_unicode=True, unique=True, verbose_name="Slug")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="软删除")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所有者",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档",
                "verbose_name_plural": "文档",
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("html", models.TextField(verbose_name="HTML 内容")),
                ("editable_blocks", models.JSONField(default=dict, verbose_name="可编辑区块")),
                ("is_auto", models.BooleanField(default=False, verbose_name="自动保存")),
                ("note", models.CharField(blank=True, max_length=200, verbose_name="版本说明")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                        verbose_name="文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档版本",
                "verbose_name_plural": "文档版本",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SlugAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "old_slug",
                    models.SlugField(allow_unicode=True, unique=True, verbose_name="旧 Slug"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slug_aliases",
                        to="documents.document",
                        verbose_name="文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slug 别名",
                "verbose_name_plural": "Slug 别名",
            },
        ),
    ]
