# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_fts5_trigram"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="node_type",
            field=models.CharField(
                choices=[
                    ("document", "文档"),
                    ("folder", "文件夹"),
                ],
                default="document",
                max_length=20,
                verbose_name="节点类型",
            ),
        ),
    ]
