# Generated by Django 6.0.5 on 2026-05-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_document_node_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversion",
            name="is_full_page",
            field=models.BooleanField(
                default=False,
                help_text="整页 HTML（含 head/style），用 iframe 渲染，不支持行内编辑。",
                verbose_name="完整 HTML 页面",
            ),
        ),
    ]
