# Generated by Django 6.0.5 on 2026-05-16 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_documentversion_is_full_page"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
        ),
        migrations.AddField(
            model_name="document",
            name="plain_text",
            field=models.TextField(blank=True, verbose_name="纯文本摘要"),
        ),
        migrations.AddField(
            model_name="document",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "私有"),
                    ("workspace", "空间内可见"),
                    ("link_shared", "链接可访问"),
                ],
                default="workspace",
                max_length=20,
                verbose_name="可见性",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nodes",
                to="workspaces.workspace",
                verbose_name="工作空间",
            ),
        ),
    ]
